package Formularios;

import poxaprofessor2.Produto;

/**
 *
 * @author Clayton Garcia
 * Mat: 2016101697
 */
public class JanelaProduto extends javax.swing.JInternalFrame {
    Produto[] vetorProdutos = new Produto[1000];
    int qteProdutos =0;
    /**
     * Creates new form JanelaProduto
     */
    public JanelaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sairBtn = new javax.swing.JButton();
        nomePCx = new javax.swing.JTextField();
        nomePLbl = new javax.swing.JLabel();
        precoLbl = new javax.swing.JLabel();
        precoCx = new javax.swing.JTextField();
        qteLbl = new javax.swing.JLabel();
        qteCx = new javax.swing.JTextField();
        cadastrarPBtn = new javax.swing.JButton();
        novoPBtn = new javax.swing.JButton();

        sairBtn.setText("Sair");
        sairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBtnActionPerformed(evt);
            }
        });

        nomePCx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePCxActionPerformed(evt);
            }
        });

        nomePLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomePLbl.setText("Nome:");

        precoLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        precoLbl.setText("Preço:");

        qteLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qteLbl.setText("Quantidade:");

        cadastrarPBtn.setText("Cadastrar");
        cadastrarPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPBtnActionPerformed(evt);
            }
        });

        novoPBtn.setText("Novo");
        novoPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoPBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(novoPBtn)
                        .addGap(73, 73, 73)
                        .addComponent(cadastrarPBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sairBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomePLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomePCx, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(qteLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qteCx))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(precoLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precoCx, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 227, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomePLbl)
                    .addComponent(nomePCx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoLbl)
                    .addComponent(precoCx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qteLbl)
                    .addComponent(qteCx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sairBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(novoPBtn)
                            .addComponent(cadastrarPBtn))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBtnActionPerformed
       System.arraycopy(vetorProdutos, 0, JanelaPrincipal.guardaProdutos, 0, qteProdutos);
       JanelaPrincipal.contProdutos = qteProdutos;
        dispose();
    }//GEN-LAST:event_sairBtnActionPerformed

    private void nomePCxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePCxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePCxActionPerformed

    private void cadastrarPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPBtnActionPerformed
        Produto NProduto = new Produto();
        NProduto.setNome(nomePCx.getText());
        NProduto.setPreco(Float.parseFloat(precoCx.getText()));
        NProduto.setQuantidade(Integer.parseInt(qteCx.getText()));       
        vetorProdutos[qteProdutos] = NProduto;
        JanelaPrincipal.lProdutos.addElement(NProduto.infos());
        JanelaPrincipal.listaProdutos.setModel(JanelaPrincipal.lProdutos);
        
        qteProdutos++;

    }//GEN-LAST:event_cadastrarPBtnActionPerformed

    private void novoPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoPBtnActionPerformed
        nomePCx.setText("");
        precoCx.setText("");
        qteCx.setText("");
        

    }//GEN-LAST:event_novoPBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarPBtn;
    private javax.swing.JTextField nomePCx;
    private javax.swing.JLabel nomePLbl;
    private javax.swing.JButton novoPBtn;
    private javax.swing.JTextField precoCx;
    private javax.swing.JLabel precoLbl;
    private javax.swing.JTextField qteCx;
    private javax.swing.JLabel qteLbl;
    private javax.swing.JButton sairBtn;
    // End of variables declaration//GEN-END:variables
}
