package Formularios;
import poxaprofessor2.Cliente;

/**
 *
 * @author Clayton Garcia
 * Mat: 2016101697
 */
public class JanelaCliente extends javax.swing.JInternalFrame {       
        Cliente[] vetorClientes = new Cliente[100];
        int qteClientes = 0;

        
    /**
     * Creates new form JanelaCliente
     */
    public JanelaCliente() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        sairBtn = new javax.swing.JButton();
        nomeLbl = new javax.swing.JLabel();
        idadeLbl = new javax.swing.JLabel();
        sexoLbl = new javax.swing.JLabel();
        sexoLbl1 = new javax.swing.JLabel();
        nomeCx = new javax.swing.JTextField();
        idadeCx = new javax.swing.JTextField();
        cpfCx = new javax.swing.JTextField();
        sexoFBtn = new javax.swing.JRadioButton();
        sexoMBtn = new javax.swing.JRadioButton();
        novoBtn = new javax.swing.JButton();
        cadastrarBtn = new javax.swing.JButton();

        sairBtn.setText("Sair");
        sairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBtnActionPerformed(evt);
            }
        });

        nomeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeLbl.setText("Nome:");

        idadeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idadeLbl.setText("Idade:");

        sexoLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sexoLbl.setText("Sexo:");

        sexoLbl1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sexoLbl1.setText("CPF:");

        nomeCx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCxActionPerformed(evt);
            }
        });

        buttonGroupSexo.add(sexoFBtn);
        sexoFBtn.setText("Feminino");

        buttonGroupSexo.add(sexoMBtn);
        sexoMBtn.setText("Masculino");

        novoBtn.setText("Novo");
        novoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoBtnActionPerformed(evt);
            }
        });

        cadastrarBtn.setText("Cadastrar");
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(novoBtn)
                        .addGap(73, 73, 73)
                        .addComponent(cadastrarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sairBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeCx, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idadeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idadeCx, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sexoLbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfCx, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sexoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sexoFBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sexoMBtn)
                        .addGap(53, 202, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLbl)
                    .addComponent(nomeCx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idadeLbl)
                    .addComponent(idadeCx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoLbl)
                    .addComponent(sexoFBtn)
                    .addComponent(sexoMBtn))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoLbl1)
                    .addComponent(cpfCx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sairBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(novoBtn)
                            .addComponent(cadastrarBtn))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBtnActionPerformed
        System.arraycopy(vetorClientes, 0, JanelaPrincipal.guardaClientes, 0, qteClientes);
        JanelaPrincipal.contClientes = qteClientes;
        dispose();
    }//GEN-LAST:event_sairBtnActionPerformed

    private void nomeCxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCxActionPerformed

    private void novoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoBtnActionPerformed
        nomeCx.setText("");
        idadeCx.setText("");
        cpfCx.setText("");
        buttonGroupSexo.clearSelection();
        
    }//GEN-LAST:event_novoBtnActionPerformed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        Cliente NCliente = new Cliente();
        NCliente.setNome(nomeCx.getText());
        NCliente.setIdade(Integer.parseInt(idadeCx.getText()));
        if(sexoFBtn.isSelected()){
            NCliente.setSexo("Feminino");
        }else if(sexoMBtn.isSelected()){
            NCliente.setSexo("Masculino");
        }
        NCliente.setCPF(cpfCx.getText());
        vetorClientes[qteClientes] = NCliente;
        JanelaPrincipal.lClientes.addElement(NCliente.infos());
        JanelaPrincipal.listaClientes.setModel(JanelaPrincipal.lClientes);
        qteClientes++;
       
    }//GEN-LAST:event_cadastrarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JTextField cpfCx;
    private javax.swing.JTextField idadeCx;
    private javax.swing.JLabel idadeLbl;
    private javax.swing.JTextField nomeCx;
    private javax.swing.JLabel nomeLbl;
    private javax.swing.JButton novoBtn;
    private javax.swing.JButton sairBtn;
    private javax.swing.JRadioButton sexoFBtn;
    private javax.swing.JLabel sexoLbl;
    private javax.swing.JLabel sexoLbl1;
    private javax.swing.JRadioButton sexoMBtn;
    // End of variables declaration//GEN-END:variables
}
